### ISSUE TITLE
update .travis.yaml to deploy to puppet-community

### ISSUE THREAD

**Issue by mkrakowitzer** [puppet-community/puppet-confluence#28]
@nibalizer could you help me out with a secure key please :)

**Comment by nibalizer** [comment]
Sure thing.

**Comment by nibalizer** [comment]
When trying to encrypt I get this:
repository not known to https://api.travis-ci.org/: puppet-community/puppet-confluence

Maybe travis needs to be told about the github change? Maybe it needs more time to sync? None of the other modules have had this issue. Probably something to document. I'll try again in a cpl hours see if it works better.

Once its working it will appear here: https://github.com/puppet-community/plumbing/pull/1/files

**Comment by mkrakowitzer** [comment]
Should be ok now, I think it needs one commit to make travis aware of the transferred repo.

**Comment by nibalizer** [comment]
https://github.com/puppet-community/plumbing/blob/master/share/travis_secrets

**Comment by mkrakowitzer** [comment]
ty
